<?xml version="1.0"?>
<!DOCTYPE FILMS [<!ELEMENT FILMS (FILM+)>
  <!ELEMENT FILM (TITRE,GENRES?,DUREE,DATE,PAYS,REALISATEUR,ACTEURS?)>
  <!ELEMENT TITRE (ORIGINAL,FRANCAIS)>
  <!ELEMENT ORIGINAL (#PCDATA)>
  <!ELEMENT FRANCAIS (#PCDATA)>
  <!ELEMENT GENRES (GENRE*)>
  <!ELEMENT GENRE (#PCDATA)>
  <!ELEMENT DUREE (#PCDATA)>
  <!ELEMENT DATE (#PCDATA)>
  <!ELEMENT PAYS (#PCDATA)>
  <!ELEMENT REALISATEUR (#PCDATA)>
  <!ELEMENT ACTEURS (ACTEUR*)>
  <!ELEMENT ACTEUR (#PCDATA)>
]>
<FILMS>
  <FILM>
    <TITRE>
      <ORIGINAL>ABAAAAAAACarne tr&#xE9;mula</ORIGINAL>
      <FRANCAIS>En chair et en os</FRANCAIS>
    </TITRE>
    <GENRES>
      <GENRE>7</GENRE>
      <GENRE>1</GENRE>
      <GENRE>6</GENRE>
    </GENRES>
    <DUREE>103</DUREE>
    <DATE>1997</DATE>
    <PAYS>Espagne</PAYS>
    <REALISATEUR>89</REALISATEUR>
    <ACTEURS>
      <ACTEUR>289</ACTEUR>
    </ACTEURS>
  </FILM>
  <FILM>
    <TITRE>
      <ORIGINAL>ACAAAAAAACarne tr&#xE9;mula</ORIGINAL>
      <FRANCAIS>En chair et en os</FRANCAIS>
    </TITRE>
    <DUREE>103</DUREE>
    <DATE>1997</DATE>
    <PAYS>Espagne</PAYS>
    <REALISATEUR>89</REALISATEUR>
    <ACTEURS>
      <ACTEUR>289</ACTEUR>
    </ACTEURS>
  </FILM>
  <FILM>
    <TITRE>
      <ORIGINAL>ADAAAAAAACarne tr&#xE9;mula</ORIGINAL>
      <FRANCAIS>En chair et en os</FRANCAIS>
    </TITRE>
    <GENRES>
      <GENRE>7</GENRE>
      <GENRE>1</GENRE>
      <GENRE>6</GENRE>
    </GENRES>
    <DUREE>103</DUREE>
    <DATE>1997</DATE>
    <PAYS>Espagne</PAYS>
    <REALISATEUR>89</REALISATEUR>
  </FILM>
</FILMS>
